services:
  bots:
    image: worker-server:latest
    build:
      context: .
      dockerfile: apps/worker-server/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - worker-server-network

networks:
  worker-server-network:
    driver: bridge